version: "3"

services:
  # Postgres
  db:
    container_name: qlue_db
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./query:/docker-entrypoint-initdb.d/
      - ./data/pgdata:/var/lib/postgresql/data
